.POSIX:
.PHONY: common
common:
	@printf "\033[1;33m[WARNING]\033[0m No test available for this project.\n"
all: common
clean: common
fclean: common
re: common
test: common
.PHONY: all clean fclean re test
